
CONFIG_N_ACTION_STEPS = 50
CONFIG_NUM_HIDDEN_LAYERS = 18
CONFIG_NUM_HEADS = 8
CONFIG_HEAD_DIM = 256
CONFIG_NUM_IMAGES = 3
CONFIG_IMAGE_PATCH_LEN = 256
CONFIG_MAX_LANGUAGE_SEQ_LEN = 48
CONFIG_MAX_STATE_DIM = 32
CONFIG_MAX_ACTION_DIM = 32
CONFIG_VLM_WIDTH = 2048
CONFIG_VLA_WIDTH = 1024
CONFIG_VLM_SEQ_LEN = (CONFIG_NUM_IMAGES * CONFIG_IMAGE_PATCH_LEN) + CONFIG_MAX_LANGUAGE_SEQ_LEN
CONFIG_VLA_SEQ_LEN = CONFIG_N_ACTION_STEPS + 1
CONFIG_TOTAL_SEQ_LEN = CONFIG_VLM_SEQ_LEN + CONFIG_VLA_SEQ_LEN


assert CONFIG_VLM_SEQ_LEN == 816
assert CONFIG_VLA_SEQ_LEN == 51
assert CONFIG_TOTAL_SEQ_LEN == 867
